export type ArenaChallenge = {
  id: string;
  title: string;
  description: string;
  category: string;
  difficulty: "Easy" | "Medium" | "Hard";
  initialCode: string;
  testCases: { name: string; expected: string }[];
  xpReward: number;
  goldReward: number;
};

export const ARENA_CHALLENGES: ArenaChallenge[] = [
  {
    id: "arena_1",
    title: "The LRU Cache Golem",
    description: "Implement an LRU Cache with get() and put() in O(1) average time.",
    category: "Data Structures",
    difficulty: "Hard",
    initialCode: `class LRUCache {\n  capacity: number;\n  cache: Map<number, number>;\n\n  constructor(capacity: number) {\n    this.capacity = capacity;\n    this.cache = new Map();\n  }\n\n  get(key: number): number {\n    if (!this.cache.has(key)) return -1;\n    const val = this.cache.get(key)!;\n    this.cache.delete(key);\n    this.cache.set(key, val);\n    return val;\n  }\n\n  put(key: number, value: number): void {\n    if (this.cache.has(key)) this.cache.delete(key);\n    this.cache.set(key, value);\n    if (this.cache.size > this.capacity) {\n      const firstKey = this.cache.keys().next().value;\n      if (firstKey !== undefined) this.cache.delete(firstKey);\n    }\n  }\n}`,
    testCases: [
      { name: "Store & get values", expected: "Pass" },
      { name: "Evict least recently used", expected: "Pass" },
    ],
    xpReward: 150,
    goldReward: 75,
  },
  {
    id: "arena_2",
    title: "The Vector Embedding Dragon",
    description: "Compute cosine similarity between two embedding vectors.",
    category: "AI",
    difficulty: "Medium",
    initialCode: `function cosineSimilarity(vecA: number[], vecB: number[]): number {\n  let dotProduct = 0;\n  let normA = 0;\n  let normB = 0;\n  for (let i = 0; i < vecA.length; i++) {\n    dotProduct += vecA[i]! * vecB[i]!;\n    normA += vecA[i]! * vecA[i]!;\n    normB += vecB[i]! * vecB[i]!;\n  }\n  return dotProduct / (Math.sqrt(normA) * Math.sqrt(normB));\n}`,
    testCases: [
      { name: "Orthogonal vectors = 0", expected: "Pass" },
      { name: "Identical vectors = 1", expected: "Pass" },
    ],
    xpReward: 200,
    goldReward: 100,
  },
  {
    id: "arena_3",
    title: "Two-Sum Slime",
    description: "Return indices of the two numbers that add up to target.",
    category: "Algorithms",
    difficulty: "Easy",
    initialCode: `function twoSum(nums: number[], target: number): [number, number] {\n  const seen = new Map<number, number>();\n  for (let i = 0; i < nums.length; i++) {\n    const need = target - nums[i]!;\n    if (seen.has(need)) return [seen.get(need)!, i];\n    seen.set(nums[i]!, i);\n  }\n  return [-1, -1];\n}`,
    testCases: [
      { name: "Finds a unique pair", expected: "Pass" },
      { name: "Handles negatives", expected: "Pass" },
    ],
    xpReward: 80,
    goldReward: 40,
  },
  {
    id: "arena_4",
    title: "Anagram Imp",
    description: "Group anagrams from a list of words.",
    category: "Algorithms",
    difficulty: "Easy",
    initialCode: `function groupAnagrams(words: string[]): string[][] {\n  const map = new Map<string, string[]>();\n  for (const word of words) {\n    const key = word.split("").sort().join("");\n    const bucket = map.get(key) ?? [];\n    bucket.push(word);\n    map.set(key, bucket);\n  }\n  return [...map.values()];\n}`,
    testCases: [
      { name: "Groups eat/tea/ate", expected: "Pass" },
      { name: "Keeps unique words alone", expected: "Pass" },
    ],
    xpReward: 90,
    goldReward: 45,
  },
  {
    id: "arena_5",
    title: "Debounce Wraith",
    description: "Write a debounce helper that only fires after quiet milliseconds.",
    category: "Frontend",
    difficulty: "Medium",
    initialCode: `function debounce<T extends (...args: unknown[]) => void>(fn: T, wait: number) {\n  let timer: ReturnType<typeof setTimeout> | undefined;\n  return (...args: Parameters<T>) => {\n    if (timer) clearTimeout(timer);\n    timer = setTimeout(() => fn(...args), wait);\n  };\n}`,
    testCases: [
      { name: "Collapses rapid calls", expected: "Pass" },
      { name: "Fires after wait", expected: "Pass" },
    ],
    xpReward: 120,
    goldReward: 60,
  },
  {
    id: "arena_6",
    title: "Deep Merge Hydra",
    description: "Deep-merge two JSON-like objects without mutating inputs.",
    category: "Frontend",
    difficulty: "Medium",
    initialCode: `function deepMerge(a: Record<string, unknown>, b: Record<string, unknown>): Record<string, unknown> {\n  const out: Record<string, unknown> = { ...a };\n  for (const [key, value] of Object.entries(b)) {\n    const current = out[key];\n    if (isObj(current) && isObj(value)) out[key] = deepMerge(current, value);\n    else out[key] = value;\n  }\n  return out;\n}\nfunction isObj(v: unknown): v is Record<string, unknown> {\n  return typeof v === "object" && v !== null && !Array.isArray(v);\n}`,
    testCases: [
      { name: "Nested keys merge", expected: "Pass" },
      { name: "Does not mutate inputs", expected: "Pass" },
    ],
    xpReward: 130,
    goldReward: 65,
  },
  {
    id: "arena_7",
    title: "URL Parser Bat",
    description: "Parse query string parameters into a record.",
    category: "Frontend",
    difficulty: "Easy",
    initialCode: `function parseQuery(search: string): Record<string, string> {\n  const params = new URLSearchParams(search.startsWith("?") ? search.slice(1) : search);\n  const out: Record<string, string> = {};\n  params.forEach((value, key) => {\n    out[key] = value;\n  });\n  return out;\n}`,
    testCases: [
      { name: "Parses a=b&c=d", expected: "Pass" },
      { name: "Handles leading ?", expected: "Pass" },
    ],
    xpReward: 70,
    goldReward: 35,
  },
  {
    id: "arena_8",
    title: "Slugify Sprite",
    description: "Turn a title into a URL-safe kebab-case slug.",
    category: "Frontend",
    difficulty: "Easy",
    initialCode: `function slugify(title: string): string {\n  return title\n    .toLowerCase()\n    .trim()\n    .replace(/[^a-z0-9\\s-]/g, "")\n    .replace(/\\s+/g, "-")\n    .replace(/-+/g, "-");\n}`,
    testCases: [
      { name: "Hello World -> hello-world", expected: "Pass" },
      { name: "Strips punctuation", expected: "Pass" },
    ],
    xpReward: 60,
    goldReward: 30,
  },
  {
    id: "arena_9",
    title: "Binary Search Knight",
    description: "Find a target in a sorted array, or return -1.",
    category: "Algorithms",
    difficulty: "Easy",
    initialCode: `function binarySearch(nums: number[], target: number): number {\n  let lo = 0;\n  let hi = nums.length - 1;\n  while (lo <= hi) {\n    const mid = Math.floor((lo + hi) / 2);\n    if (nums[mid] === target) return mid;\n    if (nums[mid]! < target) lo = mid + 1;\n    else hi = mid - 1;\n  }\n  return -1;\n}`,
    testCases: [
      { name: "Finds existing value", expected: "Pass" },
      { name: "Returns -1 when missing", expected: "Pass" },
    ],
    xpReward: 90,
    goldReward: 45,
  },
  {
    id: "arena_10",
    title: "Interval Merge Ogre",
    description: "Merge overlapping [start, end] intervals.",
    category: "Algorithms",
    difficulty: "Medium",
    initialCode: `function mergeIntervals(intervals: number[][]): number[][] {\n  const sorted = [...intervals].sort((a, b) => a[0]! - b[0]!);\n  const out: number[][] = [];\n  for (const cur of sorted) {\n    const last = out[out.length - 1];\n    if (!last || cur[0]! > last[1]!) out.push([...cur]);\n    else last[1] = Math.max(last[1]!, cur[1]!);\n  }\n  return out;\n}`,
    testCases: [
      { name: "Merges overlapping ranges", expected: "Pass" },
      { name: "Keeps disjoint ranges", expected: "Pass" },
    ],
    xpReward: 140,
    goldReward: 70,
  },
  {
    id: "arena_11",
    title: "Top-K Specter",
    description: "Return the k most frequent elements.",
    category: "Algorithms",
    difficulty: "Medium",
    initialCode: `function topKFrequent(nums: number[], k: number): number[] {\n  const freq = new Map<number, number>();\n  for (const n of nums) freq.set(n, (freq.get(n) ?? 0) + 1);\n  return [...freq.entries()]\n    .sort((a, b) => b[1] - a[1])\n    .slice(0, k)\n    .map(([n]) => n);\n}`,
    testCases: [
      { name: "Returns k keys", expected: "Pass" },
      { name: "Breaks ties stably enough", expected: "Pass" },
    ],
    xpReward: 140,
    goldReward: 70,
  },
  {
    id: "arena_12",
    title: "Valid Parens Gargoyle",
    description: "Check whether brackets are balanced.",
    category: "Algorithms",
    difficulty: "Easy",
    initialCode: `function isValid(s: string): boolean {\n  const stack: string[] = [];\n  const pairs: Record<string, string> = { ")": "(", "]": "[", "}": "{" };\n  for (const ch of s) {\n    if (ch === "(" || ch === "[" || ch === "{") stack.push(ch);\n    else if (stack.pop() !== pairs[ch]) return false;\n  }\n  return stack.length === 0;\n}`,
    testCases: [
      { name: "()[]{} is valid", expected: "Pass" },
      { name: "(] is invalid", expected: "Pass" },
    ],
    xpReward: 80,
    goldReward: 40,
  },
  {
    id: "arena_13",
    title: "Trie of Whispers",
    description: "Insert and search words in a prefix tree.",
    category: "Data Structures",
    difficulty: "Hard",
    initialCode: `class TrieNode {\n  children = new Map<string, TrieNode>();\n  end = false;\n}\nclass Trie {\n  root = new TrieNode();\n  insert(word: string) {\n    let node = this.root;\n    for (const ch of word) {\n      if (!node.children.has(ch)) node.children.set(ch, new TrieNode());\n      node = node.children.get(ch)!;\n    }\n    node.end = true;\n  }\n  search(word: string) {\n    let node = this.root;\n    for (const ch of word) {\n      const next = node.children.get(ch);\n      if (!next) return false;\n      node = next;\n    }\n    return node.end;\n  }\n}`,
    testCases: [
      { name: "Finds inserted words", expected: "Pass" },
      { name: "Rejects prefixes that are not words", expected: "Pass" },
    ],
    xpReward: 180,
    goldReward: 90,
  },
  {
    id: "arena_14",
    title: "Rate Limit Sentinel",
    description: "Allow at most N events per window per key.",
    category: "Backend",
    difficulty: "Medium",
    initialCode: `class RateLimiter {\n  constructor(private limit: number, private windowMs: number, private hits = new Map<string, number[]>()) {}\n  allow(key: string, now = Date.now()): boolean {\n    const recent = (this.hits.get(key) ?? []).filter((t) => now - t < this.windowMs);\n    if (recent.length >= this.limit) {\n      this.hits.set(key, recent);\n      return false;\n    }\n    recent.push(now);\n    this.hits.set(key, recent);\n    return true;\n  }\n}`,
    testCases: [
      { name: "Allows under the limit", expected: "Pass" },
      { name: "Blocks over the limit", expected: "Pass" },
    ],
    xpReward: 150,
    goldReward: 75,
  },
  {
    id: "arena_15",
    title: "Idempotency Key Golem",
    description: "Replay the same mutation key without double-charging.",
    category: "Backend",
    difficulty: "Medium",
    initialCode: `class IdempotencyStore {\n  private seen = new Map<string, unknown>();\n  once<T>(key: string, fn: () => T): T {\n    if (this.seen.has(key)) return this.seen.get(key) as T;\n    const value = fn();\n    this.seen.set(key, value);\n    return value;\n  }\n}`,
    testCases: [
      { name: "Runs fn once per key", expected: "Pass" },
      { name: "Returns cached result", expected: "Pass" },
    ],
    xpReward: 140,
    goldReward: 70,
  },
  {
    id: "arena_16",
    title: "Pagination Cursor Sphinx",
    description: "Slice a list with a cursor and page size.",
    category: "Backend",
    difficulty: "Easy",
    initialCode: `function paginate<T extends { id: string }>(items: T[], cursor: string | null, limit: number) {\n  const start = cursor ? items.findIndex((i) => i.id === cursor) + 1 : 0;\n  const page = items.slice(Math.max(0, start), Math.max(0, start) + limit);\n  return { page, nextCursor: page.at(-1)?.id ?? null };\n}`,
    testCases: [
      { name: "First page has no cursor", expected: "Pass" },
      { name: "Second page continues", expected: "Pass" },
    ],
    xpReward: 100,
    goldReward: 50,
  },
  {
    id: "arena_17",
    title: "JWT Claims Warden",
    description: "Decode a base64url JWT payload without verifying (sandbox only).",
    category: "Backend",
    difficulty: "Easy",
    initialCode: `function decodeJwtPayload(token: string): Record<string, unknown> {\n  const part = token.split(".")[1];\n  if (!part) return {};\n  const json = Buffer.from(part.replace(/-/g, "+").replace(/_/g, "/"), "base64").toString("utf8");\n  return JSON.parse(json);\n}`,
    testCases: [
      { name: "Reads sub claim", expected: "Pass" },
      { name: "Handles missing payload", expected: "Pass" },
    ],
    xpReward: 90,
    goldReward: 45,
  },
  {
    id: "arena_18",
    title: "SQL Injection Banisher",
    description: "Parameterize a filter instead of concatenating SQL.",
    category: "Backend",
    difficulty: "Easy",
    initialCode: `function buildUserQuery(email: string) {\n  return { sql: "select * from users where email = $1", params: [email] };\n}`,
    testCases: [
      { name: "Uses a placeholder", expected: "Pass" },
      { name: "Passes email as param", expected: "Pass" },
    ],
    xpReward: 70,
    goldReward: 35,
  },
  {
    id: "arena_19",
    title: "Retry Hydra",
    description: "Retry an async function with exponential backoff.",
    category: "Backend",
    difficulty: "Medium",
    initialCode: `async function withRetry<T>(fn: () => Promise<T>, attempts = 3): Promise<T> {\n  let last: unknown;\n  for (let i = 0; i < attempts; i++) {\n    try {\n      return await fn();\n    } catch (err) {\n      last = err;\n      await new Promise((r) => setTimeout(r, 2 ** i * 10));\n    }\n  }\n  throw last;\n}`,
    testCases: [
      { name: "Returns on first success", expected: "Pass" },
      { name: "Retries on failure", expected: "Pass" },
    ],
    xpReward: 130,
    goldReward: 65,
  },
  {
    id: "arena_20",
    title: "Event Sourcing Skeleton",
    description: "Fold events into current account balance.",
    category: "Backend",
    difficulty: "Medium",
    initialCode: `type Event = { type: "deposit" | "withdraw"; amount: number };\nfunction balance(events: Event[]): number {\n  return events.reduce((sum, e) => sum + (e.type === "deposit" ? e.amount : -e.amount), 0);\n}`,
    testCases: [
      { name: "Deposits add", expected: "Pass" },
      { name: "Withdrawals subtract", expected: "Pass" },
    ],
    xpReward: 110,
    goldReward: 55,
  },
  {
    id: "arena_21",
    title: "Prompt Template Djinn",
    description: "Interpolate {{vars}} in a prompt template safely.",
    category: "AI",
    difficulty: "Easy",
    initialCode: `function renderPrompt(template: string, vars: Record<string, string>): string {\n  return template.replace(/\\{\\{(\\w+)\\}\\}/g, (_, key: string) => vars[key] ?? "");\n}`,
    testCases: [
      { name: "Replaces known vars", expected: "Pass" },
      { name: "Unknown vars become empty", expected: "Pass" },
    ],
    xpReward: 80,
    goldReward: 40,
  },
  {
    id: "arena_22",
    title: "Chunking Colossus",
    description: "Split text into overlapping chunks for RAG.",
    category: "AI",
    difficulty: "Medium",
    initialCode: `function chunkText(text: string, size: number, overlap: number): string[] {\n  const chunks: string[] = [];\n  const step = Math.max(1, size - overlap);\n  for (let i = 0; i < text.length; i += step) {\n    chunks.push(text.slice(i, i + size));\n    if (i + size >= text.length) break;\n  }\n  return chunks;\n}`,
    testCases: [
      { name: "Respects size", expected: "Pass" },
      { name: "Creates overlap", expected: "Pass" },
    ],
    xpReward: 130,
    goldReward: 65,
  },
  {
    id: "arena_23",
    title: "Token Budget Wraith",
    description: "Trim messages until they fit a token budget (chars/4 heuristic).",
    category: "AI",
    difficulty: "Medium",
    initialCode: `function fitBudget(messages: string[], maxTokens: number): string[] {\n  const estimate = (s: string) => Math.ceil(s.length / 4);\n  const out: string[] = [];\n  let used = 0;\n  for (let i = messages.length - 1; i >= 0; i--) {\n    const cost = estimate(messages[i]!);\n    if (used + cost > maxTokens) continue;\n    out.unshift(messages[i]!);\n    used += cost;\n  }\n  return out;\n}`,
    testCases: [
      { name: "Keeps newest first", expected: "Pass" },
      { name: "Stays under budget", expected: "Pass" },
    ],
    xpReward: 150,
    goldReward: 75,
  },
  {
    id: "arena_24",
    title: "JSON Schema Gargoyle",
    description: "Validate a flat object against required string fields.",
    category: "AI",
    difficulty: "Easy",
    initialCode: `function validate(obj: Record<string, unknown>, required: string[]): boolean {\n  return required.every((key) => typeof obj[key] === "string" && String(obj[key]).length > 0);\n}`,
    testCases: [
      { name: "Passes complete objects", expected: "Pass" },
      { name: "Fails missing fields", expected: "Pass" },
    ],
    xpReward: 70,
    goldReward: 35,
  },
  {
    id: "arena_25",
    title: "Tool Router Familiar",
    description: "Pick the right tool name from a user intent string.",
    category: "AI",
    difficulty: "Easy",
    initialCode: `function routeTool(intent: string): "search" | "calendar" | "email" | "none" {\n  const t = intent.toLowerCase();\n  if (t.includes("find") || t.includes("search")) return "search";\n  if (t.includes("meet") || t.includes("schedule")) return "calendar";\n  if (t.includes("mail") || t.includes("email")) return "email";\n  return "none";\n}`,
    testCases: [
      { name: "Routes search intents", expected: "Pass" },
      { name: "Returns none when unsure", expected: "Pass" },
    ],
    xpReward: 80,
    goldReward: 40,
  },
  {
    id: "arena_26",
    title: "CSS Specificity Specter",
    description: "Score a simple selector: ids*100 + classes*10 + tags.",
    category: "Frontend",
    difficulty: "Medium",
    initialCode: `function specificity(selector: string): number {\n  const ids = (selector.match(/#/g) ?? []).length;\n  const classes = (selector.match(/\\./g) ?? []).length;\n  const tags = (selector.match(/^[a-z]+|[\\s>+~][a-z]+/gi) ?? []).length;\n  return ids * 100 + classes * 10 + tags;\n}`,
    testCases: [
      { name: "#app .btn scores 110+", expected: "Pass" },
      { name: "Plain tag is 1", expected: "Pass" },
    ],
    xpReward: 110,
    goldReward: 55,
  },
  {
    id: "arena_27",
    title: "Heap Minion",
    description: "Maintain a min-heap and pop the smallest value.",
    category: "Data Structures",
    difficulty: "Hard",
    initialCode: `class MinHeap {\n  data: number[] = [];\n  push(n: number) {\n    this.data.push(n);\n    this.data.sort((a, b) => a - b);\n  }\n  pop(): number | undefined {\n    return this.data.shift();\n  }\n}`,
    testCases: [
      { name: "Pops smallest first", expected: "Pass" },
      { name: "Handles empty pop", expected: "Pass" },
    ],
    xpReward: 170,
    goldReward: 85,
  },
];
