export type QuestCatalogItem = {
  questId: string;
  title: string;
  description: string;
  xpReward: number;
  goldReward: number;
  levelReq: number;
  category: string;
  requirements: string;
};

export const QUEST_CATALOG: QuestCatalogItem[] = [
  {
    questId: "main_ship_mvp",
    title: "Ship a MVP in 14 Days",
    description: "Scope down your core feature set, implement authentication, and deploy a live link to Vercel.",
    xpReward: 300,
    goldReward: 150,
    levelReq: 1,
    category: "Main",
    requirements: "GitHub Repository + Live Vercel/Netlify Link",
  },
  {
    questId: "side_nextauth_drizzle",
    title: "Implement NextAuth & Drizzle Schema",
    description: "Set up full authentication and connected database ORM models for your application.",
    xpReward: 150,
    goldReward: 75,
    levelReq: 1,
    category: "Side",
    requirements: "PR link or Code Sandbox proof",
  },
  {
    questId: "side_stripe_checkout",
    title: "Integrate Stripe Payment Gateway",
    description: "Add subscription or one-time payment processing for monetizing your digital app.",
    xpReward: 200,
    goldReward: 100,
    levelReq: 2,
    category: "Side",
    requirements: "Loom video showing checkout flow in sandbox mode",
  },
  {
    questId: "main_first_100_mrr",
    title: "Earn First $100 MRR",
    description: "Launch your product on Product Hunt, Twitter/X, or Indie Hackers and convert initial paying users.",
    xpReward: 500,
    goldReward: 300,
    levelReq: 2,
    category: "Main",
    requirements: "Stripe/Revenue Dashboard screenshot or Loom link",
  },
  {
    questId: "side_ai_agent_pipeline",
    title: "Deploy an AI Agent Tool",
    description: "Build an LLM-powered feature or vector search tool using OpenAI or Anthropic API.",
    xpReward: 250,
    goldReward: 125,
    levelReq: 2,
    category: "Side",
    requirements: "Live demo link or GitHub repository",
  },
  {
    questId: "main_waitlist_100",
    title: "Collect 100 Waitlist Emails",
    description: "Ship a landing page with email capture and grow a waitlist before the full product is ready.",
    xpReward: 220,
    goldReward: 110,
    levelReq: 1,
    category: "Main",
    requirements: "Live landing page + waitlist count screenshot",
  },
  {
    questId: "main_public_changelog",
    title: "Publish a Weekly Changelog",
    description: "Write 4 consecutive weekly updates documenting what you shipped.",
    xpReward: 180,
    goldReward: 90,
    levelReq: 1,
    category: "Main",
    requirements: "Changelog URL with 4 dated entries",
  },
  {
    questId: "main_first_paying_user",
    title: "Convert First Paying User",
    description: "Get one stranger (not a friend or family) to pay for your product.",
    xpReward: 400,
    goldReward: 220,
    levelReq: 2,
    category: "Main",
    requirements: "Anonymized Stripe receipt or customer email proof",
  },
  {
    questId: "main_seo_landing",
    title: "Rank a Landing Page",
    description: "Publish an SEO page that earns organic traffic from a target keyword.",
    xpReward: 260,
    goldReward: 130,
    levelReq: 2,
    category: "Main",
    requirements: "Search Console screenshot showing impressions/clicks",
  },
  {
    questId: "main_onboarding_flow",
    title: "Ship a 3-Step Onboarding",
    description: "New users should reach an aha moment in three guided steps or fewer.",
    xpReward: 210,
    goldReward: 105,
    levelReq: 1,
    category: "Main",
    requirements: "Loom of a fresh signup completing onboarding",
  },
  {
    questId: "main_error_tracking",
    title: "Add Production Error Tracking",
    description: "Wire Sentry or equivalent and prove real errors are captured in production.",
    xpReward: 170,
    goldReward: 85,
    levelReq: 1,
    category: "Main",
    requirements: "Dashboard screenshot of a captured event",
  },
  {
    questId: "main_docs_site",
    title: "Launch Public Docs",
    description: "Document setup, API, and a quickstart so users can self-serve.",
    xpReward: 190,
    goldReward: 95,
    levelReq: 1,
    category: "Main",
    requirements: "Public docs URL",
  },
  {
    questId: "main_referral_loop",
    title: "Build a Referral Loop",
    description: "Add a share/referral mechanic that can bring a second user into the product.",
    xpReward: 280,
    goldReward: 140,
    levelReq: 3,
    category: "Main",
    requirements: "Live referral flow + example invite link",
  },
  {
    questId: "main_team_invites",
    title: "Add Team Invites",
    description: "Support more than one seat so a founder can invite a collaborator.",
    xpReward: 240,
    goldReward: 120,
    levelReq: 2,
    category: "Main",
    requirements: "Loom of inviting and accepting a teammate",
  },
  {
    questId: "main_usage_limits",
    title: "Enforce Plan Limits",
    description: "Free vs paid plans must actually gate features or usage.",
    xpReward: 230,
    goldReward: 115,
    levelReq: 2,
    category: "Main",
    requirements: "Demo of a gated feature on the free plan",
  },
  {
    questId: "side_clerk_webhooks",
    title: "Sync Clerk Webhooks",
    description: "Create users in your database from Clerk user.created events.",
    xpReward: 160,
    goldReward: 80,
    levelReq: 1,
    category: "Side",
    requirements: "Webhook handler PR + Clerk event log screenshot",
  },
  {
    questId: "side_resend_email",
    title: "Send Transactional Email",
    description: "Welcome or receipt emails must send from your own domain.",
    xpReward: 150,
    goldReward: 75,
    levelReq: 1,
    category: "Side",
    requirements: "Screenshot of a delivered email in Resend/Postmark",
  },
  {
    questId: "side_postgres_indexes",
    title: "Add Missing Indexes",
    description: "Profile a slow query and add the index that makes it fast.",
    xpReward: 140,
    goldReward: 70,
    levelReq: 2,
    category: "Side",
    requirements: "Solve the pagination kata in the in-app Code Lab",
  },
  {
    questId: "side_rate_limit",
    title: "Rate-Limit Public APIs",
    description: "Protect a public endpoint from abuse with per-user or IP limits.",
    xpReward: 145,
    goldReward: 70,
    levelReq: 2,
    category: "Side",
    requirements: "Solve the rate-limiter kata in the in-app Code Lab",
  },
  {
    questId: "side_file_uploads",
    title: "Ship Secure File Uploads",
    description: "Users can upload images or files through a signed URL, not a raw disk write.",
    xpReward: 165,
    goldReward: 80,
    levelReq: 1,
    category: "Side",
    requirements: "Live upload demo or Loom",
  },
  {
    questId: "side_dark_mode",
    title: "Add a Theme Switcher",
    description: "Persist light/dark/system preference without a flash of the wrong theme.",
    xpReward: 90,
    goldReward: 45,
    levelReq: 1,
    category: "Side",
    requirements: "Live site showing persisted theme",
  },
  {
    questId: "side_e2e_tests",
    title: "Write 5 Playwright Tests",
    description: "Cover signup, a core action, and a failure path with end-to-end tests.",
    xpReward: 200,
    goldReward: 100,
    levelReq: 2,
    category: "Side",
    requirements: "CI run screenshot + test file PR",
  },
  {
    questId: "side_storybook",
    title: "Document UI in Storybook",
    description: "Publish at least 8 component stories for your design system.",
    xpReward: 130,
    goldReward: 65,
    levelReq: 1,
    category: "Side",
    requirements: "Public Storybook URL",
  },
  {
    questId: "side_openapi",
    title: "Publish an OpenAPI Spec",
    description: "Document your HTTP API so others can generate clients.",
    xpReward: 155,
    goldReward: 80,
    levelReq: 2,
    category: "Side",
    requirements: "OpenAPI URL or repo path",
  },
  {
    questId: "side_cron_jobs",
    title: "Schedule a Cron Job",
    description: "Run a daily or hourly job that actually changes production data.",
    xpReward: 140,
    goldReward: 70,
    levelReq: 2,
    category: "Side",
    requirements: "Job definition + run log",
  },
  {
    questId: "ai_rag_chat",
    title: "Ship a RAG Chat Over Your Docs",
    description: "Users can ask questions against your own documentation or knowledge base.",
    xpReward: 260,
    goldReward: 130,
    levelReq: 2,
    category: "AI",
    requirements: "Live chat demo citing retrieved snippets",
  },
  {
    questId: "ai_streaming_ui",
    title: "Stream LLM Tokens to the UI",
    description: "Show tokens as they arrive instead of waiting for the full response.",
    xpReward: 180,
    goldReward: 90,
    levelReq: 1,
    category: "AI",
    requirements: "Loom of streaming output",
  },
  {
    questId: "ai_tool_calling",
    title: "Give the Model a Tool",
    description: "An LLM must call at least one function (search, DB, or HTTP) to complete a task.",
    xpReward: 220,
    goldReward: 110,
    levelReq: 2,
    category: "AI",
    requirements: "Solve the tool-router kata in the in-app Code Lab"
  },
  {
    questId: "ai_eval_harness",
    title: "Build an Eval Set",
    description: "Score your agent on 20 golden prompts and report pass rate.",
    xpReward: 240,
    goldReward: 120,
    levelReq: 3,
    category: "AI",
    requirements: "Eval report (CSV, notebook, or dashboard)",
  },
  {
    questId: "ai_prompt_library",
    title: "Version Your Prompts",
    description: "Store prompts outside code and roll back a bad version.",
    xpReward: 150,
    goldReward: 75,
    levelReq: 2,
    category: "AI",
    requirements: "Prompt store screenshot + PR",
  },
  {
    questId: "ai_moderation",
    title: "Add Output Guardrails",
    description: "Block or rewrite unsafe model output before it reaches the user.",
    xpReward: 170,
    goldReward: 85,
    levelReq: 2,
    category: "AI",
    requirements: "Demo of a blocked prompt",
  },
  {
    questId: "ai_embeddings_search",
    title: "Semantic Search Your Data",
    description: "Replace keyword search with embeddings over real user content.",
    xpReward: 210,
    goldReward: 105,
    levelReq: 2,
    category: "AI",
    requirements: "Live search demo + index description",
  },
  {
    questId: "ai_image_pipeline",
    title: "Generate and Store Images",
    description: "Create images from a prompt and persist them to object storage.",
    xpReward: 160,
    goldReward: 80,
    levelReq: 1,
    category: "AI",
    requirements: "Generated image URL + storage proof",
  },
  {
    questId: "ai_voice_agent",
    title: "Ship a Voice Agent",
    description: "A user can talk to your product with speech-to-text and a spoken reply.",
    xpReward: 300,
    goldReward: 150,
    levelReq: 3,
    category: "AI",
    requirements: "Loom of a voice conversation",
  },
  {
    questId: "ai_cost_dashboard",
    title: "Track LLM Spend",
    description: "Show token usage and estimated cost per user or feature.",
    xpReward: 190,
    goldReward: 95,
    levelReq: 2,
    category: "AI",
    requirements: "Admin cost dashboard screenshot",
  },
  {
    questId: "ops_ci_green",
    title: "Get CI Green on Main",
    description: "Lint, typecheck, and tests must run on every pull request.",
    xpReward: 140,
    goldReward: 70,
    levelReq: 1,
    category: "DevOps",
    requirements: "GitHub Actions (or equivalent) green run",
  },
  {
    questId: "ops_preview_deploys",
    title: "Enable Preview Deploys",
    description: "Every PR gets a unique preview URL reviewers can click.",
    xpReward: 150,
    goldReward: 75,
    levelReq: 1,
    category: "DevOps",
    requirements: "PR comment with preview URL",
  },
  {
    questId: "ops_env_split",
    title: "Split Staging and Production",
    description: "Prove staging and production use different databases and keys.",
    xpReward: 180,
    goldReward: 90,
    levelReq: 2,
    category: "DevOps",
    requirements: "Env matrix screenshot or infra diagram",
  },
  {
    questId: "ops_uptime_monitor",
    title: "Add Uptime Monitoring",
    description: "Get paged or emailed if the homepage or health route fails.",
    xpReward: 130,
    goldReward: 65,
    levelReq: 1,
    category: "DevOps",
    requirements: "Monitor config + a test alert",
  },
  {
    questId: "ops_log_drain",
    title: "Centralize Logs",
    description: "Ship application logs to a searchable drain (Axiom, Datadog, etc.).",
    xpReward: 160,
    goldReward: 80,
    levelReq: 2,
    category: "DevOps",
    requirements: "Query screenshot of a real request log",
  },
  {
    questId: "ops_backup_restore",
    title: "Prove a Backup Restore",
    description: "Restore a database backup into a scratch environment.",
    xpReward: 220,
    goldReward: 110,
    levelReq: 3,
    category: "DevOps",
    requirements: "Restore log + row count proof",
  },
  {
    questId: "ops_dockerize",
    title: "Dockerize the App",
    description: "A new contributor can run the stack with docker compose up.",
    xpReward: 170,
    goldReward: 85,
    levelReq: 2,
    category: "DevOps",
    requirements: "Dockerfile + compose file in repo",
  },
  {
    questId: "ops_feature_flags",
    title: "Add Feature Flags",
    description: "Ship a dark launch that you can toggle without a redeploy.",
    xpReward: 175,
    goldReward: 90,
    levelReq: 2,
    category: "DevOps",
    requirements: "Loom toggling a flag in production",
  },
  {
    questId: "ops_load_test",
    title: "Load Test a Hot Path",
    description: "Hit your API with a realistic load and publish the results.",
    xpReward: 200,
    goldReward: 100,
    levelReq: 3,
    category: "DevOps",
    requirements: "k6/Artillery report",
  },
  {
    questId: "ops_security_headers",
    title: "Lock Down Security Headers",
    description: "CSP, HSTS, and related headers must score well on securityheaders.com.",
    xpReward: 120,
    goldReward: 60,
    levelReq: 1,
    category: "DevOps",
    requirements: "Security headers grade screenshot",
  },
  {
    questId: "mkt_launch_tweet",
    title: "Ship a Launch Thread",
    description: "Publish a launch thread or LinkedIn post that explains the problem you solve.",
    xpReward: 110,
    goldReward: 55,
    levelReq: 1,
    category: "Marketing",
    requirements: "Public post URL",
  },
  {
    questId: "mkt_indie_hackers",
    title: "Post a Build Log on IH",
    description: "Share a candid build update on Indie Hackers or a similar forum.",
    xpReward: 120,
    goldReward: 60,
    levelReq: 1,
    category: "Marketing",
    requirements: "Thread URL",
  },
  {
    questId: "mkt_demo_video",
    title: "Record a 90-Second Demo",
    description: "A stranger should understand the product without reading docs.",
    xpReward: 140,
    goldReward: 70,
    levelReq: 1,
    category: "Marketing",
    requirements: "YouTube, Loom, or Mux URL",
  },
  {
    questId: "mkt_customer_interview",
    title: "Run 5 Customer Interviews",
    description: "Talk to five people with the problem before adding another feature.",
    xpReward: 250,
    goldReward: 125,
    levelReq: 1,
    category: "Marketing",
    requirements: "Anonymized notes from 5 interviews",
  },
  {
    questId: "mkt_pricing_page",
    title: "Publish a Pricing Page",
    description: "Clear plans, a free tier or trial, and a checkout CTA.",
    xpReward: 130,
    goldReward: 65,
    levelReq: 1,
    category: "Marketing",
    requirements: "Live /pricing URL",
  },
  {
    questId: "mkt_case_study",
    title: "Write a Customer Case Study",
    description: "Document how one user got a result with your product.",
    xpReward: 180,
    goldReward: 90,
    levelReq: 2,
    category: "Marketing",
    requirements: "Published case study URL",
  },
  {
    questId: "mkt_newsletter",
    title: "Start a Builder Newsletter",
    description: "Send at least 3 issues to a real list about what you are shipping.",
    xpReward: 160,
    goldReward: 80,
    levelReq: 1,
    category: "Marketing",
    requirements: "Archive links to 3 issues",
  },
  {
    questId: "mkt_directory_listings",
    title: "List in 5 Directories",
    description: "Get listed on relevant tool directories, not just Product Hunt.",
    xpReward: 150,
    goldReward: 75,
    levelReq: 1,
    category: "Marketing",
    requirements: "List of 5 live listing URLs",
  },
  {
    questId: "mkt_affiliate",
    title: "Launch an Affiliate Offer",
    description: "Give partners a tracked link and a payout rule.",
    xpReward: 200,
    goldReward: 100,
    levelReq: 3,
    category: "Marketing",
    requirements: "Affiliate page + example tracked link",
  },
  {
    questId: "fs_realtime",
    title: "Add a Realtime Surface",
    description: "Presence, live comments, or a live board that updates without refresh.",
    xpReward: 230,
    goldReward: 115,
    levelReq: 2,
    category: "Fullstack",
    requirements: "Loom of two browsers updating live",
  },
];
