export type RaidAttackType = "SPELL" | "CRITICAL" | "DEBUG" | "ULTIMATE";

export type RaidBossCatalogItem = {
  slug: string;
  bossName: string;
  description: string;
  maxHp: number;
  goldReward: number;
  xpReward: number;
  level: number;
  weakness: string;
  phases: string[];
  attackHints: Record<RaidAttackType, string>;
};

export const RAID_ATTACKS: Record<
  RaidAttackType,
  { label: string; damage: number; description: string }
> = {
  SPELL: { label: "Class Spell", damage: 150, description: "A reliable code strike." },
  DEBUG: { label: "Debug Volley", damage: 180, description: "Bonus vs bug-type bosses." },
  CRITICAL: { label: "Critical Refactor", damage: 250, description: "High damage, high swagger." },
  ULTIMATE: { label: "Ship Ultimate", damage: 400, description: "Heavy hit. Use when the raid is almost over." },
};

export const RAID_BOSSES: RaidBossCatalogItem[] = [
  {
    slug: "deprecated-dependency",
    bossName: "The Bug Overlord: Deprecated Dependency",
    description: "A level 5 terror clogging the guild build pipeline. It summons peer-dependency hydras every phase.",
    maxHp: 2000,
    goldReward: 600,
    xpReward: 1200,
    level: 5,
    weakness: "Lockfiles",
    phases: ["Resolve tree", "Deduplicate", "Delete node_modules (ritual)"],
    attackHints: {
      SPELL: "pnpm why the cursed package",
      DEBUG: "Reproduce the install on a clean CI runner",
      CRITICAL: "Replace the library with a maintained fork",
      ULTIMATE: "Delete the dependency and rewrite the 40 lines it wrapped",
    },
  },
  {
    slug: "n-plus-one",
    bossName: "The N+1 Query Hydra",
    description: "Every page load grows a new head. It feeds on missing indexes and lazy ORM defaults.",
    maxHp: 2400,
    goldReward: 700,
    xpReward: 1400,
    level: 6,
    weakness: "Includes / joins",
    phases: ["Spot the loop", "Batch the reads", "Add the index"],
    attackHints: {
      SPELL: "Log every query in development",
      DEBUG: "Explain analyze the hot path",
      CRITICAL: "Replace the loop with one joined query",
      ULTIMATE: "Add a covering index and a dataloader",
    },
  },
  {
    slug: "memory-leak-kraken",
    bossName: "Memory Leak Kraken",
    description: "A long-running Node process that never lets go of listeners, timers, or closures.",
    maxHp: 2800,
    goldReward: 800,
    xpReward: 1600,
    level: 7,
    weakness: "Heap snapshots",
    phases: ["Reproduce growth", "Find the retainer", "Unsubscribe"],
    attackHints: {
      SPELL: "Take a heap snapshot after 5 minutes",
      DEBUG: "Track EventEmitter listener counts",
      CRITICAL: "Clear the interval and abort the fetch",
      ULTIMATE: "Restart is not a fix — ship the patch",
    },
  },
  {
    slug: "cors-wraith",
    bossName: "CORS Wraith of the Staging Origin",
    description: "It only appears in production, whispering Access-Control-Allow-Origin: null.",
    maxHp: 1600,
    goldReward: 450,
    xpReward: 900,
    level: 3,
    weakness: "Allowlists",
    phases: ["Reproduce in prod headers", "Fix the allowlist", "Preflight OPTIONS"],
    attackHints: {
      SPELL: "Inspect the preflight in DevTools",
      DEBUG: "Log Origin on the server",
      CRITICAL: "Allow the real production origin only",
      ULTIMATE: "Stop reflecting * with credentials",
    },
  },
  {
    slug: "hydration-mismatch",
    bossName: "Hydration Mismatch Phantom",
    description: "Server HTML and client React cannot agree on the time, the random id, or the theme.",
    maxHp: 1800,
    goldReward: 500,
    xpReward: 1000,
    level: 4,
    weakness: "Determinism",
    phases: ["Find the extra text node", "Gate client-only UI", "Suppress the false warning"],
    attackHints: {
      SPELL: "Render the same clock on server and client",
      DEBUG: "Disable extensions that inject DOM",
      CRITICAL: "Move Math.random behind useEffect",
      ULTIMATE: "A blocking theme script before paint",
    },
  },
  {
    slug: "race-condition-djinn",
    bossName: "Race Condition Djinn",
    description: "Two requests, one row, infinite “it works on my machine.”",
    maxHp: 2600,
    goldReward: 750,
    xpReward: 1500,
    level: 7,
    weakness: "Transactions",
    phases: ["Write a failing test", "Lock or upsert", "Idempotency key"],
    attackHints: {
      SPELL: "Add an idempotency key column",
      DEBUG: "Run the handler twice in parallel",
      CRITICAL: "SERIALIZABLE or a unique constraint",
      ULTIMATE: "Outbox pattern so webhooks cannot double-fire",
    },
  },
  {
    slug: "css-specificity-titan",
    bossName: "CSS Specificity Titan",
    description: "It wears !important like armor. Your Tailwind class never lands.",
    maxHp: 1500,
    goldReward: 400,
    xpReward: 850,
    level: 2,
    weakness: "Layers",
    phases: ["Delete the leftover stylesheet", "Move to @layer", "Burn !important"],
    attackHints: {
      SPELL: "Inspect computed styles",
      DEBUG: "Find the winning selector",
      CRITICAL: "Delete the old global CSS file",
      ULTIMATE: "One design-token source of truth",
    },
  },
  {
    slug: "flaky-test-golem",
    bossName: "Flaky Test Golem",
    description: "Green locally, red on CI, and it only fails on Tuesdays.",
    maxHp: 2200,
    goldReward: 650,
    xpReward: 1300,
    level: 6,
    weakness: "Deterministic clocks",
    phases: ["Quarantine", "Un-sleep the test", "Stub time and network"],
    attackHints: {
      SPELL: "Replace wait(5000) with a finder",
      DEBUG: "Seed the RNG and freeze Date.now",
      CRITICAL: "Mock the network, not the world",
      ULTIMATE: "Delete the test that asserts a race",
    },
  },
  {
    slug: "secret-leaker",
    bossName: "The Secret Leaker",
    description: "API keys in the client bundle, .env committed, and a webhook unsigned.",
    maxHp: 3000,
    goldReward: 900,
    xpReward: 1800,
    level: 8,
    weakness: "Server-only env",
    phases: ["Rotate every leaked key", "Move secrets server-side", "Add secret scanning"],
    attackHints: {
      SPELL: "grep the bundle for sk_live",
      DEBUG: "Enable GitHub secret scanning",
      CRITICAL: "Rotate and invalidate the leaked token",
      ULTIMATE: "A pre-commit hook that blocks .env",
    },
  },
  {
    slug: "bundle-behemoth",
    bossName: "Bundle Size Behemoth",
    description: "A 4MB client chunk that ships moment, lodash, and three unused icon packs.",
    maxHp: 2100,
    goldReward: 620,
    xpReward: 1250,
    level: 5,
    weakness: "Dynamic imports",
    phases: ["Analyze the graph", "Split the route", "Tree-shake the icons"],
    attackHints: {
      SPELL: "Run the bundle analyzer",
      DEBUG: "Find the fattest import in the waterfall",
      CRITICAL: "dynamic() the chart library",
      ULTIMATE: "Delete moment and use Intl.DateTimeFormat",
    },
  },
  {
    slug: "timezone-basilisk",
    bossName: "Timezone Basilisk",
    description: "Meetings at 2am, invoices on the wrong day, and DST that ate a cron job.",
    maxHp: 1900,
    goldReward: 540,
    xpReward: 1100,
    level: 4,
    weakness: "UTC storage",
    phases: ["Store UTC", "Render local", "Test America/New_York + UTC"],
    attackHints: {
      SPELL: "Save timestamps as ISO UTC",
      DEBUG: "Reproduce with TZ=Pacific/Auckland",
      CRITICAL: "Never parse a date with new Date(yyyy-mm-dd) in local TZ",
      ULTIMATE: "A timezone-aware scheduler, not setInterval",
    },
  },
  {
    slug: "rate-limit-raptor",
    bossName: "Rate Limit Raptor",
    description: "It pecks the public API until 429s cascade into a support queue.",
    maxHp: 2300,
    goldReward: 680,
    xpReward: 1350,
    level: 6,
    weakness: "Token buckets",
    phases: ["Identify the hot endpoint", "Add a limiter", "Return Retry-After"],
    attackHints: {
      SPELL: "Cap anonymous traffic first",
      DEBUG: "Log 429s by IP and user",
      CRITICAL: "Sliding window per user + route",
      ULTIMATE: "Queue the work instead of dropping it",
    },
  },
  {
    slug: "deadlock-dragon",
    bossName: "Deadlock Dragon",
    description: "Two transactions, two locks, zero progress. The pool is full of waiting claws.",
    maxHp: 2700,
    goldReward: 780,
    xpReward: 1550,
    level: 7,
    weakness: "Lock order",
    phases: ["Capture the wait graph", "Unify lock order", "Shorten the transaction"],
    attackHints: {
      SPELL: "Log pg_stat_activity wait events",
      DEBUG: "Reproduce with two parallel checkouts",
      CRITICAL: "Always lock user then invoice, never the reverse",
      ULTIMATE: "Move non-critical writes out of the txn",
    },
  },
  {
    slug: "redirect-serpent",
    bossName: "Infinite Redirect Serpent",
    description: "www to apex to locale to trailing-slash to www again. Browsers give up. SEO dies.",
    maxHp: 1700,
    goldReward: 480,
    xpReward: 950,
    level: 3,
    weakness: "One canonical host",
    phases: ["Map the hop chain", "Pick one canonical", "301 once"],
    attackHints: {
      SPELL: "curl -I the live URL",
      DEBUG: "Disable the middleware that rewrites twice",
      CRITICAL: "One redirect: host + https + slash policy",
      ULTIMATE: "Canonical tags that match the final URL",
    },
  },
  {
    slug: "schema-drift-sphinx",
    bossName: "Schema Drift Sphinx",
    description: "Prod is three migrations behind staging. The Sphinx asks riddles about columns that do not exist.",
    maxHp: 2500,
    goldReward: 720,
    xpReward: 1450,
    level: 6,
    weakness: "Migrate on deploy",
    phases: ["Diff prod vs repo", "Backfill safely", "Gate deploys on migrate"],
    attackHints: {
      SPELL: "Dump the production schema",
      DEBUG: "Find the missing unique index",
      CRITICAL: "Expand/contract, never rewrite in place",
      ULTIMATE: "CI that fails if drizzle generate is dirty",
    },
  },
  {
    slug: "cold-start-colossus",
    bossName: "Cold Start Colossus",
    description: "The first request after idle takes 4.8s. Users bounce. The Colossus sleeps between deploys.",
    maxHp: 2000,
    goldReward: 600,
    xpReward: 1200,
    level: 5,
    weakness: "Warm paths",
    phases: ["Measure TTFB", "Trim boot work", "Keep a warm instance"],
    attackHints: {
      SPELL: "Trace the serverless init",
      DEBUG: "Move secrets fetch out of the hot path",
      CRITICAL: "Lazy-load the 12MB SDK",
      ULTIMATE: "A scheduled ping plus a thinner runtime",
    },
  },
  {
    slug: "cache-invalidation-lich",
    bossName: "Cache Invalidation Lich",
    description: "Stale HTML, stale CDN, stale Redis. The Lich cannot be killed, only expired correctly.",
    maxHp: 2900,
    goldReward: 850,
    xpReward: 1700,
    level: 8,
    weakness: "Tag revalidation",
    phases: ["Name the cache layers", "Tag every entry", "Purge on write"],
    attackHints: {
      SPELL: "List every cache between user and DB",
      DEBUG: "Reproduce with a write then an immediate read",
      CRITICAL: "revalidateTag on the mutation path",
      ULTIMATE: "One invalidation bus, not five TTLs",
    },
  },
];

export function raidDamage(attackType: RaidAttackType, weaknessBonus = false): number {
  const base = RAID_ATTACKS[attackType]?.damage ?? RAID_ATTACKS.SPELL.damage;
  return weaknessBonus ? Math.round(base * 1.15) : base;
}
