import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Geist, Geist_Mono, Inter, Jersey_10 } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import { ClerkProvider } from '@clerk/nextjs'
import { shadcn } from '@clerk/ui/themes'
import { Toaster } from "@/components/ui/sonner";
import { COLOR_SCHEME_COOKIE, parseColorScheme } from "@/lib/color-scheme";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const GameFont=Jersey_10({
  subsets:['latin'],
  variable:'--font-game',
  weight:['400'],
})

const inter=Inter({
  subsets:["latin"],
  variable:"--font-inter",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const scheme = parseColorScheme((await cookies()).get(COLOR_SCHEME_COOKIE)?.value);

  return (
    <html lang="en" suppressHydrationWarning className="dark" data-scheme={scheme}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} 
        ${GameFont.variable} ${inter.variable}
        antialiased`}
      >
        <ClerkProvider
          appearance={{ theme: shadcn }}
          signInUrl="/sign-in"
          signUpUrl="/sign-up"
          signInFallbackRedirectUrl="/dashboard"
          signUpFallbackRedirectUrl="/onboarding"
        >
          <Provider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
          >
            {children}
          </Provider>
          <Toaster/>
        </ClerkProvider>
      </body>
    </html>
  );
}
